config/routes.rb
Southernhopheads::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  # static pages
  get  'about',    :to => 'home#about'
  get  'admin',    :to => 'home#admin'

  # contact us page
  get  'contact',  :to => 'messages#new', :as => :contact
  post 'contact',  :to => 'messages#create', :as => :contact

  # calendar
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  
  #search
  match '/search', :to => 'search#index'

  # users
  devise_scope :user do
    get "signup", :to => "devise/registrations#new"
    get "signin", :to => "devise/sessions#new"
  end
  devise_for :users
  resources :users, :only => [:index, :show, :update, :destroy], :shallow => true do
    resources :payments
  end

  match '/users/unsubscribe/:signature' => 'users#unsubscribe', :as => 'unsubscribe'

  get  'preferences', :to => 'preferences#edit'
  post 'preferences', :to => 'preferences#update'  
  get  'profile',     :to => 'profile#edit'
  post 'profile',     :to => 'profile#update'
  
  # articles
  get '/articles/queue', :to => 'articles#queue', :as => :article_queue
  match '/articles/:id/publish' => 'articles#publish', :as => :publish_article
  match '/articles/:id/email'   => 'articles#email',   :as => :email_article
  match '/articles/:id/bump'    => 'articles#bump',    :as => :bump_article
  resources :articles, :shallow => true do
    resources :comments
  end

  # events
  get '/events/queue', :to => 'events#queue', :as => :event_queue
  match '/events/:id/publish' => 'events#publish', :as => :publish_event
  match '/events/:id/email'   => 'events#email',   :as => :email_event
  match 'events/:id/bump'     => 'events#bump',    :as => :bump_event
  resources :events, :shallow => true do
    resources :comments
  end

  # forums
  resources :forums, :shallow => true do
    resources :posts do
      resources :comments
    end
  end

  # breweries/beers
  resources :breweries, :shallow => true do
    resources :beers do
      resources :reviews
    end
  end
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id             :integer          not null, primary key
#  title          :string(255)
#  content        :text
#  user_id        :integer
#  start_at       :datetime
#  end_at         :datetime
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  allow_comments :boolean
#  location       :string(255)
#  event          :boolean
#  published      :boolean          default(FALSE)
#  featured       :boolean          default(FALSE)
#

class Article < ActiveRecord::Base
  attr_accessible :content, :title, :allow_comments, :start_at, :end_at, :location, :event, :featured

  validates :title, :presence => true, :length => { :maximum => 100 }
  validates :content, :presence => true, :length => { :maximum => 3000 }

  has_event_calendar
  
  belongs_to :user
  has_many :comments, :as => :commentable, :dependent => :destroy
 
  scope :published, where(:published => true)
  scope :not_published, where(:published => false)
  scope :events, where(:event => true)
  scope :nonevents, where(:event => false)
  scope :featured, where(:featured => true)
  scope :not_featured, where(:featured => false)

  def self.created_before(time)
    where("created_at < ?", time)
  end

  def self.created_after(time)
    where("created_at > ?", time)
  end

  def self.starts_before(time)
    where("start_at < ?", time)
  end

  def self.starts_after(time)
    where("start_at > ?", time)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, :only => [ :new, :create, :edit, :update, :destroy, :queue, :publish, :email ]

  def index
    @articles = Article.published.order('updated_at DESC').paginate(:page => params[:page], :per_page => 10)
  end

  def new
    authorize! :new, Article, :message => 'Not authorized to create articles.'
    @article = Article.new
  end

  def create
    authorize! :create, Article, :message => 'Not authorized to create articles.'
    @article = Article.new(params[:article])
    @article.user_id = current_user.id
    @article.end_at = @article.start_at if @article.end_at.nil?
    @article.featured = true
    if @article.save
      flash[:notice] = 'Article created. Thank you!'
      redirect_to @article
    else
      render :action => 'new'
    end
  end

  def show
    if user_signed_in?
      if current_user.has_role?(:admin)
        @article = @commentable = Article.find(params[:id])
      else
        @article = @commentable = Article.published.find(params[:id])
      end
    else
      @article = @commentable = Article.published.find(params[:id])
    end
    @comments = @article.comments.paginate(:page => params[:page], :per_page => 10)
  end

  def edit
    @article = Article.find(params[:id])
    authorize! :edit, @article, :message => 'Not authorized to edit articles.'
  end

  def update
    @article = Article.find(params[:id])
    authorize! :update, @article, :message => 'Not authorized to update articles.'
    if @article.update_attributes(params[:article])
      flash[:notice] = 'Article has been updated.'
      redirect_to @article
    else
      render :action => 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    authorize! :destroy, @article, :message => 'Not authorized to delete articles.'
    @article.destroy
    flash[:notice] = 'Article has been deleted.'
    redirect_to root_path
  end

  def queue
    authorize! :queue, Article, :message => 'Not authorized to access article queue.'
    @articles = Article.not_published.order('updated_at DESC')
  end

  def publish
    @article = Article.find(params[:id])
    authorize! :publish, @article, :message => 'Not authorized to publish this article.'
    @article.published = true
    if @article.save
      flash[:notice] = 'Article has been published.'
    else
      flash[:error] = 'There was an error publishing this article.'
    end
    redirect_to article_queue_path
  end

  def email
    @article = Article.find(params[:id])
    authorize! :email, @article, :message => 'Not authorized to email this article.'
    @recipients = User.wants_emails_about_articles
    if @article.valid? and !@recipients.empty?
      @recipients.each do |u|
        UserMailer.email_article(u, @article).deliver
      end
      flash[:notice] = 'Your message has been sent! Thank you!'
      redirect_to @article
    else
      flash[:error] = 'Error. Email not sent.'
      redirect_to @article
    end
  end

  def bump
    @article = Article.find(params[:id])
    authorize! :bump, @article, :message => 'Not authorized to bump this article.'
    @article.created_at = Time.zone.now
    if @article.save
      flash[:notice] = 'Article creation date has been bumped.'
    else
      flash[:error] = 'Error. Unable to save article.'
    end
    redirect_to @article
  end
end

app/views/articles/_article.html.erb
<li>
  <span class="articles-index-title"><%= link_to article.title, article %><%= "&nbsp;<span class=\"label\">Event</span>".html_safe if article.event %></span>
  <br />
  <span class="articles-index-user">posted by <%= link_to article.user.name, article.user %></span>
  <span class="articles-index-date"><%= article.created_at.strftime("%B %d, %Y") %></span>
</li>

app/views/articles/_fields.html.erb
<%= f.input :title, :autofocus => true %>
<%= f.input :content, :as => :text %>
<%= f.input :allow_comments, :label => false, :inline_label => 'Allow comments', :input_html => { :checked => true } %>

app/views/articles/_instructions.html.erb
<div class="well">
  <p>Article should be in HTML. At minimum, you should wrap all paragraphs in 'p' tags (e.g. <strong>&lt;p&gt;</strong>Hi there!<strong>&lt;/p&gt;</strong>). Please remember to close your tags (note the '/' in the second tag).</p>
  <p>To display only a summary of the article on the front page, wrap content in the following comment tags:</p>
  <p><strong>&lt;!-- summary --&gt;</strong> ... <strong>&lt;!-- summary_end --&gt;</strong></p>
  <p>Any remaining content outside of these tags will only be displayed when viewing the full article. If no summary section is included, all content will be displayed on both the main page and the full article details.</p>
</div>

app/views/articles/edit.html.erb
<% provide(:title, "Edit Article") %>

<div class="post">
  <h2 class="clearfix title">Edit Article</h2>
  <p class="clearfix meta"></p>
  <div class="entry">
    <%= render 'instructions' %>
    <%= simple_form_for @article do |f| %>
      <%= f.error_notification %>
      <%= display_base_errors @article %>
      <%= render 'fields', :f => f %>
      <%= f.button :submit, "Update Article", :class => 'btn-primary' %>
    <% end %>
  </div>
</div>

app/views/articles/index.html.erb
<% provide(:title, "Articles") %>

<div id="articles-index" class="post">
  <h2 class="clearfix title">Articles</h2>
  <p class="clearfix meta"></p>
  <div class="entry">
    <ul>
      <% alt = false %>
      <% @articles.each do |article| %>
        <%= alt == true ? '<li class="alt">'.html_safe : '<li>'.html_safe %>
          <% alt = !alt %>
          <span class="articles-index-title"><%= link_to article.title, article %><%= "&nbsp;<span class=\"label\">Event</span>".html_safe if article.event %></span>
          <br />
          <span class="articles-index-user">posted by <%= link_to article.user.name, article.user %></span>
          <span class="articles-index-date"><%= article.created_at.strftime("%B %d, %Y") %></span>
        </li>
      <% end %>
    </ul>
    <%= will_paginate %>
  </div>
</div>

app/views/articles/new.html.erb
<% provide(:title, "New Article") %>

<div class="post">
  <h2 class="title">New Article</h2>
  <div class="entry">
    <%= render 'instructions' %>
    <%= simple_form_for @article do |f| %>
      <%= f.error_notification %>
      <%= display_base_errors @article %>
      <%= render 'fields', :f => f %>
      <%= f.button :submit, "Create Article", :class => 'btn-primary' %>
    <% end %>
  </div>
</div>

app/views/articles/queue.html.erb
<% provide(:title, "Article Queue") %>
<% postalt = false %>

<div class="alert">
  <a class="close" data-dismiss="alert">&#215;</a>
  <div id="flash_notice"><strong>Note:</strong> These articles have not yet been published.</div>
</div>

<% if @articles.count > 0 %>
  <% @articles.each do |article| %>
    <%= postalt == true ? '<div class="post post-alt">'.html_safe : '<div class="post">'.html_safe %>
      <% postalt = !postalt %>
      <h2 class="clearfix title"><%= link_to sanitize(article.title), article %></h2>
      <p class="clearfix meta"><span class="date"><%= article.created_at.strftime("%B %d, %Y") %></span><span class="posted">Posted by <%= link_to User.find(article.user_id).name, user_path(article.user_id) %></span></p>
      <div class="entry">
        <%=
          # Show only the summary if summary comment tags are found.
          if /<!-- summary -->(.+)<!-- summary_end -->/m =~ article.content then
            sanitize($1, :tags => ALLOWED_TAGS, :attributes => ALLOWED_ATTRIBUTES).html_safe
          else
            sanitize(article.content, :tags => ALLOWED_TAGS, :attributes => ALLOWED_ATTRIBUTES).html_safe
          end
        %>
        <p class="links"><%= link_to "Read More", article, :class => 'btn' %><span class="comment-count"><%= link_to("Comments (#{article.comments.count})", article) if article.comments.count > 0 %></span></p>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="post">
    <div class="entry">
      <h5>No unpublished articles in the queue! \o/</h5>
    </div>
  </div>
<% end %>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>

<% if user_signed_in? %>
  <% if current_user.has_role?(:admin) and !@article.published %>
    <div class="alert">
      <a class="close" data-dismiss="alert">&#215;</a>
      <div id="flash_notice"><strong>Note:</strong> This article has not been published yet. Click <%= link_to 'here', publish_article_path(@article), :data => { :confirm => "Are you sure you want to publish this article?" } %> to publish it.</div>
    </div>
  <% end %>
<% end %>

<div id="article">
  <div class="post">
    <h2 class="clearfix title">
      <%= link_to sanitize(@article.title), @article %>
      <div class="admin-controls pull-right">
        <% if can? :bump, @article %>
          <%= link_to '<i class="icon-circle-arrow-up" title="Bump article"></i>'.html_safe, bump_article_path(@article.id), :data => { :confirm => "Are you sure you want to bump this article?" } %>
        <% end %>
        <% if can? :email, @article %>
          <%= link_to '<i class="icon-envelope" title="Email article"></i>'.html_safe, email_article_path(@article.id), :data => { :confirm => "Are you sure you want to email this article to users that have opted-in?" } %>
        <% end %>
        <% if can? :update, @article %>
          <%= link_to '<i class="icon-edit" title="Edit article"></i>'.html_safe, edit_article_path(@article.id) %>
        <% end %>
        <% if can? :destroy, @article %>
          <%= link_to '<i class="icon-trash" title="Delete article"></i>'.html_safe, @article, :method => :delete, :data => { :confirm => "Are you sure you want to delete this article? This will also delete any associated comments. THIS ACTION CANNOT BE UNDONE!" } %>
        <% end %>
      </div>
    </h2>
    <p class="clearfix meta"><span class="date"><%= @article.created_at.strftime("%B %d, %Y") %></span><span class="posted">Posted by <%= link_to User.find(@article.user_id).name, user_path(@article.user_id) %></span></p>
    <div class="entry">
      <%= sanitize(@article.content, :tags => ALLOWED_TAGS, :attributes => ALLOWED_ATTRIBUTES).gsub('&lt;!-- summary', '<!-- summary').html_safe %>
    </div>
  </div>
</div>

<div id="comments">
  <div class="post post-alt">
    <h2 class="clearfix title">Comments</h2>
    <p class="clearfix meta"></p>
    <div class="entry">
      <% if @comments.size > 0 %>
        <%= render @comments %>
        <%= will_paginate @comments %>
      <% else %>
        <p>No comments yet.</p>
      <% end %>
      <h3>New Comment</h3>
      <% if user_signed_in? and can? :create, Comment %>
        <% if @article.allow_comments %>
          <%= simple_form_for [@article, Comment.new] do |f| %>
            <%= f.text_area :content, :as => :text %>
            <%= f.button :submit, "Add comment", :class => 'btn-primary' %>
          <% end %>
        <% else %>
          <p>Commenting has been disabled for this article.</p>
        <% end %>
      <% else %>
        <p>Must be <%= link_to 'signed in', new_user_session_path %> to comment.</p>
      <% end %>
    </div>
  </div>
</div>