config/routes.rb
Southernhopheads::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  # static pages
  get  'about',    :to => 'home#about'
  get  'admin',    :to => 'home#admin'

  # contact us page
  get  'contact',  :to => 'messages#new', :as => :contact
  post 'contact',  :to => 'messages#create', :as => :contact

  # calendar
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  
  #search
  match '/search', :to => 'search#index'

  # users
  devise_scope :user do
    get "signup", :to => "devise/registrations#new"
    get "signin", :to => "devise/sessions#new"
  end
  devise_for :users
  resources :users, :only => [:index, :show, :update, :destroy], :shallow => true do
    resources :payments
  end

  match '/users/unsubscribe/:signature' => 'users#unsubscribe', :as => 'unsubscribe'

  get  'preferences', :to => 'preferences#edit'
  post 'preferences', :to => 'preferences#update'  
  get  'profile',     :to => 'profile#edit'
  post 'profile',     :to => 'profile#update'
  
  # articles
  get '/articles/queue', :to => 'articles#queue', :as => :article_queue
  match '/articles/:id/publish' => 'articles#publish', :as => :publish_article
  match '/articles/:id/email'   => 'articles#email',   :as => :email_article
  match '/articles/:id/bump'    => 'articles#bump',    :as => :bump_article
  resources :articles, :shallow => true do
    resources :comments
  end

  # events
  get '/events/queue', :to => 'events#queue', :as => :event_queue
  match '/events/:id/publish' => 'events#publish', :as => :publish_event
  match '/events/:id/email'   => 'events#email',   :as => :email_event
  match 'events/:id/bump'     => 'events#bump',    :as => :bump_event
  resources :events, :shallow => true do
    resources :comments
  end

  # forums
  resources :forums, :shallow => true do
    resources :posts do
      resources :comments
    end
  end

  # breweries/beers
  resources :breweries, :shallow => true do
    resources :beers do
      resources :reviews
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :only => [ :admin ]

  def index
    @articles_and_events = find_featured_articles_and_events(:order => "created_at DESC", :limit => 6)
  end

  def about
    @president = User.find(31) # justin 31
    @vp = User.find(11) # josh 11
    @secretary = User.find(23) # z 23
    @treasurer = User.find(2) # hunter 2
    @webmaster = User.find(3) # brian 3
  end
  
  def admin
    authorize! :manage, User
    @user_count = User.count
    @article_count = Article.published.count
    @event_count = Event.published.count
    @comment_count = Comment.count
    @new_users = User.order('created_at DESC').limit(4)
    @new_comments = Comment.order('created_at DESC').limit(4)
    @unconfirmed_users = User.where(:confirmed_at => [nil, false])
  end

  private

    #
    # Fetch the most recent articles and events, sorted and limited together as one resource.
    # This returns an array of hashes with each array element representing one row of returned data.
    #
    def find_featured_articles_and_events(options = { :order => nil, :limit => nil })
      results = Array.new
      cols = [:id, :title, :content, :user_id, :start_at, :end_at, :location, :allow_comments, :featured, :published, :created_at, :updated_at]

      query  = "(SELECT #{cols.join(', ')}, 'article' AS type"
      query << " FROM articles WHERE published = 1 AND featured = 1)"
      query << " UNION"
      query << " (SELECT #{cols.join(', ')}, 'event' AS type"
      query << " FROM events WHERE published = 1 AND featured = 1)"
      query << " ORDER BY #{options[:order]}" unless options[:order].nil?
      query << " LIMIT #{options[:limit]}" unless options[:limit].nil?

      rows = ActiveRecord::Base.connection.execute(query)
      cols.push(:type)
      rows.each do |row|
        results.push(Hash[*cols.zip(row).flatten])
      end

      return results
    end
end

app/views/home/about.html.erb
<% provide(:title, "About Us") %>

<div id="about-page">

  <div id="about-us" class="post">
    <h2 class="clearfix title">About The Southern HopHeads</h2>
    <p class="clearfix meta"></p>
    <div class="entry">
      <p><strong>You've reached the homepage for the Southern HopHeads! We're a homebrew club based in Southern Pines, North Carolina.</strong></p>
      <%= image_tag('winter_public_pour_2013-group.jpg') %>
      <span class="caption">"Cheers!"</span>
      <p>Over the past several years, we have watched the craft beer market and the interest in homebrewing explode in this area. Being as the nearest club is in Fayetteville, we decided to start our own. Our goal is to create a community for other homebrewers to get together, share ideas, advice and, of course, great beer.</p>
      <p>If you're looking to find others who share your passion for beer and brewing then you've come to the right place! Please have a look through the site and feel free to sign up to receive announcements and participate in the forums. The club has regular events and meetings so don't forget to check the calendar!</p>
      <p><strong>And remember… Don't worry, relax, have a homebrew!</strong></p>  
    </div>
  </div>

  <div id="about-officers" class="post post-alt">
    <h2 class="clearfix title">Club Officers</h2>
    <p class="clearfix meta"></p>
    <div class="entry">
      <table>
        <tr>
          <td class="spaceUnder">
            <%= gravatar_for @president, :size => 60 %>
            President<br />
            <%= link_to "Justin S.", @president %>
          </td>
          <td class="spaceUnder">
            <%= gravatar_for @vp, :size => 60 %>
            Vice President<br />
            <%= link_to "Josh K.", @vp %>
          </td>
        </tr>
        <tr>
          <td class="spaceUnder">
            <%= gravatar_for @secretary, :size => 60 %>
            Secretary<br />
            <%= link_to "Brian Z.", @secretary %>
          </td>
          <td class="spaceUnder">
            <%= gravatar_for @treasurer, :size => 60 %>
            Treasurer<br />
            <%= link_to "Hunter M.", @treasurer %>
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <%= gravatar_for @webmaster, :size => 60 %>
            Webmaster<br />
            <%= link_to "Brian W.", @webmaster %>
          </td>
        </tr>
      </table>
    </div>
  </div>

  <div id="about-constitution" class="post">
    <h2 class="clearfix title">Constitution</h2>
    <p class="clearfix meta"></p>
    <div class="entry">
      <p><strong><em>Article 1</em></strong></p>
      <p><strong>Section 1: Name</strong></p>
      <p>The official club name of this homebrewers association is "Southern Hopheads"</p>
      <p><strong>Section 2: Purpose</strong></p>
      <p>
        <ul>
          <li>To create a community of like-minded enthusiasts</li>
          <li>To encourage and accept fellow homebrewers in the community</li>
          <li>To advance our knowledge of beer and brewing</li>
          <li>To have fun!</li>
        </ul>
      </p>
      <p><strong>Section 3: Membership</strong></p>
      <p><strong>Section 4: Headquarters</strong></p>
      <p>Currently, most of our meetings are held at Triangle Wine Company in Southern Pines but events are occasionally held at other local establishments.</p>
    </div>
  </div>

</div>

app/views/home/admin.html.erb
<% provide(:title, "Admin Dashboard") %>

<div class="post">
  <h2 class="clearfix title">Admin Dashboard</h2>
  <p class="clearfix meta"></p>
  <div class="entry">

    <h4>Statistics</h4>
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Resource</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Users</td>
          <td><%= @user_count %></td>
        </tr>
        <tr>
          <td>Articles</td>
          <td><%= @article_count %></td>
        </tr>
        <tr>
          <td>Events</td>
          <td><%= @event_count %></td>
        </tr>
        <tr>
          <td>Comments</td>
          <td><%= @comment_count %></td>
        </tr>
      </tbody>
    </table>

    <% if @new_users.count > 0 %>
      <h4>New Users</h4>
      <table class="table table-condensed">
        <thead>
          <tr>
            <th>Username</th>
            <th>Email</th>
            <th>Joined</th>
          </tr>
        </thead>
        <tbody>
          <% @new_users.each do |u| %>
            <tr>
              <td><%= link_to u.name, u %></td>
              <td><%= u.email %></td>
              <td><%= u.created_at %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>

    <% if @unconfirmed_users.count > 0 %>
      <h4>Unconfirmed Users</h4>
      <table class="table table-condensed">
        <thead>
          <tr>
            <th>Username</th>
            <th>Email</th>
            <th>Joined</th>
          </tr>
        </thead>
        <tbody>
          <% @unconfirmed_users.each do |u| %>
            <tr>
              <td><%= link_to u.name, u %></td>
              <td><%= u.email %></td>
              <td><%= u.created_at %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>      

    <% if @new_comments.count > 0 %>
      <h4>Latest Comments</h4>
      <table class="table table-condensed">
        <thead>
          <tr>
            <th>User</th>
            <th>Comment</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @new_comments.each do |c| %>
            <tr>
              <td>
                <%= gravatar_for c.user, :size => 30 %><br />
                <%= link_to c.user.name, c.user %>
              </td>
              <td><%= RedCloth.new(strip_tags(c.content)).to_html.html_safe %></td>
              <td><%= link_to c.commentable_type, c.commentable_type.constantize.unscoped.find(c.commentable_id), :class => "btn btn-mini" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>

  </div>
</div>

app/views/home/index.html.erb
<% provide(:title, "Home") %>
<% postalt = true %>

<div id="greeting" class="clearfix">
  <%= image_tag('rough_logo_goldgreen_150.png') %>
  <p>Welcome! We're a homebrew club based in Southern Pines, North Carolina! Please have a look around and feel free to <%= link_to 'sign up', new_user_registration_path %> to be able to access all features of the site.</p>
  <ul>
    <li><%= link_to 'About Us', about_path, :class => 'btn btn-mini' %></li>
    <li><%= link_to 'Sign Up', new_user_registration_path, :class => 'btn btn-mini' %></li>
    <li><%= link_to 'Events', calendar_path, :class => 'btn btn-mini' %></li>
  </ul>
</div>


<% if @articles_and_events.count > 0 %>
  <% @articles_and_events.each do |ae| %>
    <%= postalt == true ? '<div class="post post-alt">'.html_safe : '<div class="post">'.html_safe %>
      <% postalt = !postalt %>
      <h2 class="clearfix title"><%= link_to sanitize(ae[:title]), "#{ae[:type]}s/#{ae[:id]}" %></h2>
      <p class="clearfix meta"><span class="date"><%= ae[:created_at].strftime("%B %d, %Y") %></span><span class="posted">Posted by <%= link_to User.find(ae[:user_id]).name, user_path(ae[:user_id]) %></span></p>
      <% if ae[:type] == 'event' %>
        <div class="event-details">
          <h5>When: <%= ae[:start_at].to_time.strftime("%A, %B %d at %I:%M%p") %> <%= "(noon)" if ae[:start_at].strftime("%I:%M%p") == "12:00PM" %></h5>
          <h5>Where: <%= sanitize(ae[:location]) %></h5>
        </div>
      <% end %>
      <div class="entry">
        <p>
          <%=
            # Show only the summary if summary comment tags are found.
            if /<!-- summary -->(.+)<!-- summary_end -->/m =~ ae[:content] then
              sanitize($1, :tags => ALLOWED_TAGS, :attributes => ALLOWED_ATTRIBUTES).html_safe
            else
              sanitize(ae[:content], :tags => ALLOWED_TAGS, :attributes => ALLOWED_ATTRIBUTES).html_safe
            end
          %>
        </p>
        <% comment_count = Comment.where(:commentable_type => ae[:type].classify, :commentable_id => ae[:id]).count %>
        <p class="links"><%= link_to "Read More", "#{ae[:type]}s/#{ae[:id]}", :class => 'btn' %><span class="comment-count"><%= link_to("Comments (#{comment_count})", "#{ae[:type]}s/#{ae[:id]}") if comment_count > 0 %></span></p>
      </div>
    </div>
  <% end %>
  <%= postalt == true ? '<div class="post post-alt">'.html_safe : '<div class="post">'.html_safe %>
    <p><%= link_to "More articles", articles_path, :class => 'center center-text' %></p>
  </div>
<% end %>