config/routes.rb
Southernhopheads::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  # static pages
  get  'about',    :to => 'home#about'
  get  'admin',    :to => 'home#admin'

  # contact us page
  get  'contact',  :to => 'messages#new', :as => :contact
  post 'contact',  :to => 'messages#create', :as => :contact

  # calendar
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  
  #search
  match '/search', :to => 'search#index'

  # users
  devise_scope :user do
    get "signup", :to => "devise/registrations#new"
    get "signin", :to => "devise/sessions#new"
  end
  devise_for :users
  resources :users, :only => [:index, :show, :update, :destroy], :shallow => true do
    resources :payments
  end

  match '/users/unsubscribe/:signature' => 'users#unsubscribe', :as => 'unsubscribe'

  get  'preferences', :to => 'preferences#edit'
  post 'preferences', :to => 'preferences#update'  
  get  'profile',     :to => 'profile#edit'
  post 'profile',     :to => 'profile#update'
  
  # articles
  get '/articles/queue', :to => 'articles#queue', :as => :article_queue
  match '/articles/:id/publish' => 'articles#publish', :as => :publish_article
  match '/articles/:id/email'   => 'articles#email',   :as => :email_article
  match '/articles/:id/bump'    => 'articles#bump',    :as => :bump_article
  resources :articles, :shallow => true do
    resources :comments
  end

  # events
  get '/events/queue', :to => 'events#queue', :as => :event_queue
  match '/events/:id/publish' => 'events#publish', :as => :publish_event
  match '/events/:id/email'   => 'events#email',   :as => :email_event
  match 'events/:id/bump'     => 'events#bump',    :as => :bump_event
  resources :events, :shallow => true do
    resources :comments
  end

  # forums
  resources :forums, :shallow => true do
    resources :posts do
      resources :comments
    end
  end

  # breweries/beers
  resources :breweries, :shallow => true do
    resources :beers do
      resources :reviews
    end
  end
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id             :integer          not null, primary key
#  title          :string(255)
#  content        :text
#  user_id        :integer
#  start_at       :datetime
#  end_at         :datetime
#  location       :string(255)
#  allow_comments :boolean          default(TRUE)
#  featured       :boolean          default(FALSE)
#  published      :boolean          default(FALSE)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Event < ActiveRecord::Base
  attr_accessible :title, :content, :start_at, :end_at, :location, :allow_comments, :featured

  validates :title, :presence => true, :length => { :maximum => 100 }
  validates :content, :presence => true, :length => { :maximum => 3000 }

  has_event_calendar
  
  belongs_to :user
  has_many :comments, :as => :commentable, :dependent => :destroy

  scope :featured, where(:featured => true)
  scope :not_featured, where(:featured => false)
  scope :published, where(:published => true)
  scope :not_published, where(:published => false)

  def self.created_before(time)
    where("created_at < ?", time)
  end

  def self.created_after(time)
    where("created_at > ?", time)
  end

  def self.starts_before(time)
    where("start_at < ?", time)
  end

  def self.starts_after(time)
    where("start_at > ?", time)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, :only => [ :new, :create, :edit, :update, :destroy, :queue, :publish, :email ]

  def index
    @events = Event.published.order('updated_at DESC').paginate(:page => params[:page], :per_page => 10)
  end

  def new
    authorize! :new, Event, :message => 'Not authorized to create events.'
    @event = Event.new
  end

  def create
    authorize! :create, Event, :message => 'Not authorized to create events.'
    @event = Event.new(params[:event])
    @event.user_id = current_user.id
    @event.end_at = @event.start_at if @event.end_at.nil?
    if @event.save
      flash[:notice] = 'Event created. Thank you!'
      redirect_to @event
    else
      render :action => 'new'
    end
  end

  def show
    if user_signed_in?
      if current_user.has_role?(:admin)
        @event = @commentable = Event.find(params[:id])
      else
        @event = @commentable = Event.published.find(params[:id])
      end
    else
      @event = @commentable = Event.published.find(params[:id])
    end
    @comments = @event.comments.paginate(:page => params[:page], :per_page => 10)
  end

  def edit
    @event = Event.find(params[:id])
    authorize! :edit, @event, :message => 'Not authorized to edit events.'
  end

  def update
    @event = Event.find(params[:id])
    authorize! :update, @event, :message => 'Not authorized to update events.'
    if @event.update_attributes(params[:event])
      flash[:notice] = 'Event has been updated.'
      redirect_to @event
    else
      render :action => 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    authorize! :destroy, @event, :message => 'Not authorized to delete events.'
    @event.destroy
    flash[:notice] = 'Event has been deleted.'
    redirect_to root_path
  end

  def queue
    authorize! :queue, Event, :message => 'Not authorized to access event queue.'
    @events = Event.not_published.order('updated_at DESC')
  end

  def publish
    @event = Event.find(params[:id])
    authorize! :publish, @event, :message => 'Not authorized to publish this event.'
    @event.published = true
    if @event.save
      flash[:notice] = 'Event has been published.'
    else
      flash[:error] = 'There was an error publishing this event.'
    end
    redirect_to event_queue_path
  end

  def email
    @event = Event.find(params[:id])
    authorize! :email, @event, :message => 'Not authorized to email this event.'
    @recipients = User.wants_emails_about_events
    if @event.valid? and !@recipients.empty?
      @recipients.each do |u|
        UserMailer.email_event(u, @event).deliver
      end
      flash[:notice] = 'Your message has been sent! Thank you!'
      redirect_to @event
    else
      flash[:error] = 'Error. Email not sent.'
      redirect_to @event
    end
  end

  def bump
    @event = Event.find(params[:id])
    authorize! :bump, @event, :message => 'Not authorized to bump this event.'
    @event.created_at = Time.zone.now
    if @event.save
      flash[:notice] = 'Event creation date has been bumped.'
    else
      flash[:error] = 'Error. Unable to save event.'
    end
    redirect_to @event
  end
end

app/views/events/_event.html.erb
<li>
  <span class="events-index-title"><%= link_to event.title, event %></span>
  <br />
  <span class="events-index-user">posted by <%= link_to event.user.name, event.user %></span>
  <span class="events-index-date"><%= event.created_at.strftime("%B %d, %Y") %></span>
</li>

app/views/events/_fields.html.erb
<%= f.input :title, :autofocus => true %>
<hr />
<%= f.label 'Start time' %>
<%= f.datetime_picker 'start_at', :dateFormat => "yy-mm-dd" %>
<%= f.label 'End time (optional)' %>
<%= f.datetime_picker 'end_at', :dateFormat => "yy-mm-dd" %>
<%= f.input :location %>
<hr />
<%= f.input :content, :as => :text %>
<%= f.input :featured, :label => false, :inline_label => "Feature this event on the front page" %>
<%= f.input :allow_comments, :label => false, :inline_label => 'Allow comments', :input_html => { :checked => true } %>

app/views/events/_instructions.html.erb
<div class="well">
  <p>Event content should be in HTML. At minimum, you should wrap all paragraphs in 'p' tags (e.g. <strong>&lt;p&gt;</strong>Hi there!<strong>&lt;/p&gt;</strong>). Please remember to close your tags (note the '/' in the second tag).</p>
  <p>To display only a summary of the event on the front page, wrap content in the following comment tags:</p>
  <p><strong>&lt;!-- summary --&gt;</strong> ... <strong>&lt;!-- summary_end --&gt;</strong></p>
  <p>Any remaining content outside of these tags will only be displayed when viewing the full event. If no summary section is included, all content will be displayed on both the main page and the full event details.</p>
</div>

app/views/events/edit.html.erb
<% provide(:title, "Edit Event") %>

<div class="post">
  <h2 class="clearfix title">Edit Event</h2>
  <p class="clearfix meta"></p>
  <div class="entry">
    <%= render 'instructions' %>
    <%= simple_form_for @event do |f| %>
      <%= f.error_notification %>
      <%= display_base_errors @event %>
      <%= render 'fields', :f => f %>
      <%= f.button :submit, "Update Event", :class => 'btn-primary' %>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<% provide(:title, "Events") %>

<div id="events-index" class="post">
  <h2 class="clearfix title">Events</h2>
  <p class="clearfix meta"></p>
  <div class="entry">
    <ul>
      <% alt = false %>
      <% @events.each do |event| %>
        <%= alt == true ? '<li class="alt">'.html_safe : '<li>'.html_safe %>
          <% alt = !alt %>
          <span class="events-index-title"><%= link_to event.title, event %></span>
          <br />
          <span class="events-index-user">posted by <%= link_to event.user.name, event.user %></span>
          <span class="events-index-date"><%= event.created_at.strftime("%B %d, %Y") %></span>
        </li>
      <% end %>
    </ul>
    <%= will_paginate %>
  </div>
</div>

app/views/events/new.html.erb
<% provide(:title, "New Event") %>

<div class="post">
  <h2 class="title">New Event</h2>
  <div class="entry">
    <%= render 'instructions' %>
    <%= simple_form_for @event do |f| %>
      <%= f.error_notification %>
      <%= display_base_errors @event %>
      <%= render 'fields', :f => f %>
      <%= f.button :submit, "Create Event", :class => 'btn-primary' %>
    <% end %>
  </div>
</div>

app/views/events/queue.html.erb
<% provide(:title, "Event Queue") %>
<% postalt = false %>

<div class="alert">
  <a class="close" data-dismiss="alert">&#215;</a>
  <div id="flash_notice"><strong>Note:</strong> These events have not yet been published.</div>
</div>

<% if @events.count > 0 %>
  <% @events.each do |event| %>
    <%= postalt == true ? '<div class="post post-alt">'.html_safe : '<div class="post">'.html_safe %>
      <% postalt = !postalt %>
      <h2 class="clearfix title"><%= link_to sanitize(event.title), event %></h2>
      <p class="clearfix meta"><span class="date"><%= event.created_at.strftime("%B %d, %Y") %></span><span class="posted">Posted by <%= link_to User.find(event.user_id).name, user_path(event.user_id) %></span></p>
      <div class="event-details">
        <h5>When: <%= event.start_at.strftime("%A, %B %d at %I:%M%p") %> <%= "(noon)" if event.start_at.strftime("%I:%M%p") == "12:00PM" %></h5>
        <h5>Where: <%= sanitize(event.location) %></h5>
      </div>
      <div class="entry">
        <%=
          # Show only the summary if summary comment tags are found.
          if /<!-- summary -->(.+)<!-- summary_end -->/m =~ event.content then
            sanitize($1, :tags => ALLOWED_TAGS, :attributes => ALLOWED_ATTRIBUTES).html_safe
          else
            sanitize(event.content, :tags => ALLOWED_TAGS, :attributes => ALLOWED_ATTRIBUTES).html_safe
          end
        %>
        <p class="links"><%= link_to "Read More", event, :class => 'btn' %><span class="comment-count"><%= link_to("Comments (#{event.comments.count})", event) if event.comments.count > 0 %></span></p>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="post">
    <div class="entry">
      <h5>No unpublished events in the queue! \o/</h5>
    </div>
  </div>
<% end %>

app/views/events/show.html.erb
<% provide(:title, @event.title) %>

<% if user_signed_in? %>
  <% if current_user.has_role?(:admin) and !@event.published %>
    <div class="alert">
      <a class="close" data-dismiss="alert">&#215;</a>
      <div id="flash_notice"><strong>Note:</strong> This event has not been published yet. Click <%= link_to 'here', publish_event_path(@event), :data => { :confirm => "Are you sure you want to publish this event?" } %> to publish it.</div>
    </div>
  <% end %>
<% end %>

<div id="event">
  <div class="post">
    <h2 class="clearfix title">
      <%= link_to sanitize(@event.title), @event %>
      <div class="admin-controls pull-right">
        <% if can? :bump, @event %>
          <%= link_to '<i class="icon-circle-arrow-up" title="Bump event"></i>'.html_safe, bump_event_path(@event.id), :data => { :confirm => "Are you sure you want to bump this event?" } %>
        <% end %>
        <% if can? :email, @event %>
          <%= link_to '<i class="icon-envelope" title="Email event"></i>'.html_safe, email_event_path(@event.id), :data => { :confirm => "Are you sure you want to email this event to users that have opted-in?" } %>
        <% end %>
        <% if can? :update, @event %>
          <%= link_to '<i class="icon-edit" title="Edit event"></i>'.html_safe, edit_event_path(@event.id) %>
        <% end %>
        <% if can? :destroy, @event %>
          <%= link_to '<i class="icon-trash" title="Delete event"></i>'.html_safe, @event, :method => :delete, :data => { :confirm => "Are you sure you want to delete this event? This will also delete any associated comments. THIS ACTION CANNOT BE UNDONE!" } %>
        <% end %>
      </div>
    </h2>
    <p class="clearfix meta"><span class="date"><%= @event.created_at.strftime("%B %d, %Y") %></span><span class="posted">Posted by <%= link_to User.find(@event.user_id).name, user_path(@event.user_id) %></span></p>
    <div class="event-details">
      <h5>When: <%= @event.start_at.strftime("%A, %B %d at %I:%M%p") %> <%= "(noon)" if @event.start_at.strftime("%I:%M%p") == "12:00PM" %></h5>
      <h5>Where: <%= sanitize(@event.location) %></h5>
    </div>
    <div class="entry">
      <%= sanitize(@event.content, :tags => ALLOWED_TAGS, :attributes => ALLOWED_ATTRIBUTES).gsub('&lt;!-- summary', '<!-- summary').html_safe %>
    </div>
  </div>
</div>

<div id="comments">
  <div class="post post-alt">
    <h2 class="clearfix title">Comments</h2>
    <p class="clearfix meta"></p>
    <div class="entry">
      <% if @comments.size > 0 %>
        <%= render @comments %>
        <%= will_paginate @comments %>
      <% else %>
        <p>No comments yet.</p>
      <% end %>
      <h3>New Comment</h3>
      <% if user_signed_in? and can? :create, Comment %>
        <% if @event.allow_comments %>
          <%= simple_form_for [@event, Comment.new] do |f| %>
            <%= f.text_area :content, :as => :text %>
            <%= f.button :submit, "Add comment", :class => 'btn-primary' %>
          <% end %>
        <% else %>
          <p>Commenting has been disabled for this event.</p>
        <% end %>
      <% else %>
        <p>Must be <%= link_to 'signed in', new_user_session_path %> to comment.</p>
      <% end %>
    </div>
  </div>
</div>