config/routes.rb
Southernhopheads::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  # static pages
  get  'about',    :to => 'home#about'
  get  'admin',    :to => 'home#admin'

  # contact us page
  get  'contact',  :to => 'messages#new', :as => :contact
  post 'contact',  :to => 'messages#create', :as => :contact

  # calendar
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  
  #search
  match '/search', :to => 'search#index'

  # users
  devise_scope :user do
    get "signup", :to => "devise/registrations#new"
    get "signin", :to => "devise/sessions#new"
  end
  devise_for :users
  resources :users, :only => [:index, :show, :update, :destroy], :shallow => true do
    resources :payments
  end

  match '/users/unsubscribe/:signature' => 'users#unsubscribe', :as => 'unsubscribe'

  get  'preferences', :to => 'preferences#edit'
  post 'preferences', :to => 'preferences#update'  
  get  'profile',     :to => 'profile#edit'
  post 'profile',     :to => 'profile#update'
  
  # articles
  get '/articles/queue', :to => 'articles#queue', :as => :article_queue
  match '/articles/:id/publish' => 'articles#publish', :as => :publish_article
  match '/articles/:id/email'   => 'articles#email',   :as => :email_article
  match '/articles/:id/bump'    => 'articles#bump',    :as => :bump_article
  resources :articles, :shallow => true do
    resources :comments
  end

  # events
  get '/events/queue', :to => 'events#queue', :as => :event_queue
  match '/events/:id/publish' => 'events#publish', :as => :publish_event
  match '/events/:id/email'   => 'events#email',   :as => :email_event
  match 'events/:id/bump'     => 'events#bump',    :as => :bump_event
  resources :events, :shallow => true do
    resources :comments
  end

  # forums
  resources :forums, :shallow => true do
    resources :posts do
      resources :comments
    end
  end

  # breweries/beers
  resources :breweries, :shallow => true do
    resources :beers do
      resources :reviews
    end
  end
end

app/models/payment.rb
# == Schema Information
#
# Table name: payments
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  payment_type :string(255)      default("single"), not null
#  payment_date :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Payment < ActiveRecord::Base
  attr_accessible :payment_date, :payment_type, :as => :treasurer
  validates :payment_type, :presence => true
  validates :payment_date, :presence => true
  belongs_to :user
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_filter :authenticate_user!, :only => [ :index, :new, :create, :edit, :update, :destroy ]

  def index
    authorize! :index, Payment, :message => 'You are not authorized to see payment indexes.'
    @user = User.find(params[:user_id])
    @payment = @user.payment
  end

  def new
    authorize! :new, Payment, :message => 'You are not authorized to make new payments.'
    @user = User.find(params[:user_id])
    @payment = Payment.new
  end

  def create
    authorize! :create, Payment, :message => 'You are not authorized to create payments.'
    @user = User.find(params[:user_id])
    @payment = @user.build_payment(params[:payment], :as => :treasurer)
    if @payment.save
      flash[:notice] = 'Payment created. Thank you.'
      redirect_to users_path
    else
      render :action => 'new'
    end
  end

  def edit
    @payment = Payment.find(params[:id])
    authorize! :edit, @payment, :message => 'You are not authorized to edit payments.'
  end

  def update
    authorize! :update, Payment, :message => 'You are not authorized to update payments.'
    @payment = Payment.find(params[:id])
    if @payment.update_attributes(params[:payment], :as => :treasurer)
      flash[:notice] = 'Payment has been updated.'
      redirect_to users_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @payment = Payment.find(params[:id])
    authorize! :destroy, @payment, :message => 'Not authorized to delete payments.'
    @payment.destroy
    flash[:notice] = 'Payment has been deleted.'
    redirect_to forums_path
  end

  def show
    @payment = Payment.find(params[:id])

  end
end

app/views/payments/_fields.html.erb
      <%= f.label 'Payment Date' %>
      <%= f.datetime_picker :payment_date, :dateFormat => "yy-mm-dd" %><br />
      <%= f.input :payment_type, :collection => [['single', 'Single ($15)'], ['group', 'Group ($20)']], :label_method => :last, :value_method => :first, :as => :radio_buttons, :item_wrapper_class => 'inline' %>
      

app/views/payments/edit.html.erb
<% provide(:title, "Edit Payment") %>

<div class="post">
  <h2 class="clearfix title">Edit Payment</h2>
  <p class="clearfix meta"></p>
  <div class="entry">
    <%= simple_form_for @payment, :html => { :class => 'form-vertical' } do |f| %>
      <%= f.error_notification %>
      <%= display_base_errors @payment %>
      <%= render 'fields', :f => f %>
      <%= f.button :submit, "Submit", :class => 'btn-primary' %>
    <% end %>
  </div>
</div>

app/views/payments/index.html.erb
<% provide(:title, "Payments for #{@user.name}") %>

<div class="post">
  <div id="user-payment-index">
    <h2 class="clearfix title">Payments for <%= @user.name %></h2>
    <p class="clearfix meta"></p>
    <div class="entry">
      <% if @payment.nil? %>
        <h5>No payments for this user.</h5>
        <% if current_user.has_role? :treasurer %>
          <p><%= link_to "Add Payment", new_user_payment_path(@user), :class => 'btn btn-mini' %></p>
        <% end %>
      <% else %>
        <table class="table table-condensed">
          <thead>
            <tr>
              <th>Paid Date</th>
              <th>Payment Type</th>
              <th>Expires</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @payment.payment_date.strftime('%Y-%m-%d') %></td>
              <td><%= @payment.payment_type %></td>
              <td><%= (@payment.payment_date + 1.year).strftime('%Y-%m-%d') %></td>
              <td><%= link_to "Edit", edit_payment_path(@payment.id), :class => 'btn btn-mini' %></td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/payments/new.html.erb
<% provide(:title, "New Payment") %>

<div class="post">
  <h2 class="clearfix title">New Payment</h2>
  <p class="clearfix meta"></p>
  <div class="entry">
    <%= simple_form_for [@user, @payment], :html => { :class => 'form-vertical' } do |f| %>
      <%= f.error_notification %>
      <%= display_base_errors @payment %>
      <%= render 'fields', :f => f %>
      <%= f.button :submit, "Submit", :class => 'btn-primary' %>
    <% end %>
  </div>
</div>

app/views/payments/show.html.erb
<% provide(:title, "Payment for #{@payment.user.name}") %>

<div class="post">
  <div id="user-payment-index">
    <h2 class="clearfix title">Payment for <%= @payment.user.name %></h2>
    <p class="clearfix meta"></p>
    <div class="entry">
      <% if @payment.nil? %>
        <h5>No payments for this user.</h5>
        <% if current_user.has_role? :treasurer %>
          <p><%= link_to "Add Payment", new_user_payment_path(@user), :class => 'btn btn-mini' %></p>
        <% end %>
      <% else %>
        <table class="table table-condensed">
          <thead>
            <tr>
              <th>Paid Date</th>
              <th>Payment Type</th>
              <th>Expires</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @payment.payment_date.strftime('%Y-%m-%d') %></td>
              <td><%= @payment.payment_type %></td>
              <td><%= (@payment.payment_date + 1.year).strftime('%Y-%m-%d') %></td>
              <td><%= link_to "Edit", edit_payment_path(@payment.id), :class => 'btn btn-mini' %></td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>